/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.quanlilotrinh;

import DungChung.StringDungChung;
import connectSQL.LopKetNoi;
import controller.ChuyenManHinhView;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.sql.ResultSet;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import module.Chuyen;
import module.ThoiGianHoatDong;
import moduledao.ChuyenDao;
import moduledao.ThoiGianHoatDongDao;
import view.JPanelQuanLiLoTrinh;
import view.JPanelQuanLiTuyen;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class JPanelChuyen extends javax.swing.JPanel {

    private float vanToc = 60;
    private ThoiGianHoatDongDao thoiGianDao;
    private DefaultTableModel tbmThoiGian, tbmChuyen;
    //==================================
    private String thongTin = "THÔNG TIN";
    private String them = "THÊM";
    private String sua = "SỬA";
    //================================
    private int hangThoiGian = -1;
    private int hangChuyen = -1;

    /**
     * Creates new form JPanelQuanLiChuyen
     */
    public JPanelChuyen() {
        initComponents();
        thoiGianDao = new ThoiGianHoatDongDao();
        tbmChuyen = (DefaultTableModel) jtbChuyen.getModel();
        tbmThoiGian = (DefaultTableModel) jtbThoiGianHoatDong.getModel();
        ChuyenDao.loadDSChuyenVaoBang(LopKetNoi.select("select * from Chuyen"), tbmChuyen);
        thoiGianDao.loadDSThoiGianVaoBang(LopKetNoi.select("select * from KhoangThoiGianHoatDong"), tbmThoiGian);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdlThongTinThoiGian = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jlbTenDialog = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfMaThoiGian = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtfTenThoiGian = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jlbMaThoiGian = new javax.swing.JLabel();
        jlbTenThoiGian = new javax.swing.JLabel();
        jlbNgayBatDau = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jlbNgayKetThuc = new javax.swing.JLabel();
        btnXacNhanThoiGian = new javax.swing.JButton();
        jdcNgayBatDau = new com.toedter.calendar.JDateChooser();
        jdcNgayKetThuc = new com.toedter.calendar.JDateChooser();
        jdlThongTinChuyen = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jlbTenDialogChuyen = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtfMaChuyen = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jtfMaTuyen = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jlbMaTuyen = new javax.swing.JLabel();
        jlbKhoiHanh = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        btnXacNhanChuyen = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jtfTGKhoiHanh = new javax.swing.JTextField();
        cbbThoiGian = new javax.swing.JComboBox<>();
        cbbTrangThai = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jtfTGDen = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jlbMaChuyen = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbChuyen = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jtfTimKiem = new javax.swing.JTextField();
        cbbTiemKiem = new javax.swing.JComboBox<>();
        cbbSapXep = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnThongTIn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtbThoiGianHoatDong = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        btnThem1 = new javax.swing.JButton();
        btnSua1 = new javax.swing.JButton();
        btnXoa1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jtfTimKiem1 = new javax.swing.JTextField();
        cbbTiemKiem1 = new javax.swing.JComboBox<>();
        cbbSapXep1 = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        btnThongTIn1 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();

        jdlThongTinThoiGian.setMinimumSize(new java.awt.Dimension(500, 511));

        jlbTenDialog.setBackground(new java.awt.Color(102, 255, 255));
        jlbTenDialog.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlbTenDialog.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbTenDialog.setText("THÔNG TIN CHI TIẾT");

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel3.setText("MÃ:");

        jtfMaThoiGian.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel4.setText("TÊN: ");

        jtfTenThoiGian.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel6.setText("NGÀY BẮT ĐẦU:");

        jLabel7.setBackground(new java.awt.Color(204, 204, 204));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel7.setText("NGÀY KẾT THÚC:");

        jlbMaThoiGian.setBackground(new java.awt.Color(255, 255, 255));
        jlbMaThoiGian.setForeground(new java.awt.Color(255, 51, 51));
        jlbMaThoiGian.setText("abc");

        jlbTenThoiGian.setBackground(new java.awt.Color(255, 255, 255));
        jlbTenThoiGian.setForeground(new java.awt.Color(255, 51, 51));
        jlbTenThoiGian.setText("abc");

        jlbNgayBatDau.setBackground(new java.awt.Color(255, 255, 255));
        jlbNgayBatDau.setForeground(new java.awt.Color(255, 51, 51));
        jlbNgayBatDau.setText("abc");

        jLabel17.setText("Định dạng: dd/MM/yyyy");

        jLabel18.setText("Định dạng: dd/MM/yyyy");

        jlbNgayKetThuc.setBackground(new java.awt.Color(255, 255, 255));
        jlbNgayKetThuc.setForeground(new java.awt.Color(255, 51, 51));
        jlbNgayKetThuc.setText("abc");

        btnXacNhanThoiGian.setBackground(new java.awt.Color(255, 255, 255));
        btnXacNhanThoiGian.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnXacNhanThoiGian.setText("XÁC NHẬN");
        btnXacNhanThoiGian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanThoiGianActionPerformed(evt);
            }
        });

        jdcNgayBatDau.setBackground(new java.awt.Color(255, 255, 255));
        jdcNgayBatDau.setDateFormatString("dd/MM/yyyy");
        jdcNgayBatDau.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jdcNgayKetThuc.setBackground(new java.awt.Color(255, 255, 255));
        jdcNgayKetThuc.setDateFormatString("dd/MM/yyyy");
        jdcNgayKetThuc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbTenDialog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlbNgayKetThuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlbNgayBatDau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlbTenThoiGian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlbMaThoiGian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtfMaThoiGian)
                            .addComponent(jtfTenThoiGian)
                            .addComponent(jdcNgayBatDau, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jdcNgayKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(btnXacNhanThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jlbTenDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfMaThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbMaThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jtfTenThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbTenThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jdcNgayBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbNgayBatDau)
                .addGap(20, 20, 20)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jdcNgayKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbNgayKetThuc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(btnXacNhanThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );

        javax.swing.GroupLayout jdlThongTinThoiGianLayout = new javax.swing.GroupLayout(jdlThongTinThoiGian.getContentPane());
        jdlThongTinThoiGian.getContentPane().setLayout(jdlThongTinThoiGianLayout);
        jdlThongTinThoiGianLayout.setHorizontalGroup(
            jdlThongTinThoiGianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jdlThongTinThoiGianLayout.setVerticalGroup(
            jdlThongTinThoiGianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jlbTenDialogChuyen.setBackground(new java.awt.Color(102, 255, 255));
        jlbTenDialogChuyen.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlbTenDialogChuyen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbTenDialogChuyen.setText("THÔNG TIN CHI TIẾT");

        jLabel10.setBackground(new java.awt.Color(204, 204, 204));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel10.setText("MÃ:");

        jtfMaChuyen.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel11.setBackground(new java.awt.Color(204, 204, 204));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel11.setText("MÃ TUYẾN:");

        jtfMaTuyen.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel12.setBackground(new java.awt.Color(204, 204, 204));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel12.setText("KHOẢNG THỜI GIAN:");

        jLabel19.setBackground(new java.awt.Color(204, 204, 204));
        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel19.setText("TG KHỞI HÀNH:");

        jlbMaTuyen.setBackground(new java.awt.Color(255, 255, 255));
        jlbMaTuyen.setForeground(new java.awt.Color(255, 51, 51));
        jlbMaTuyen.setText("a");

        jlbKhoiHanh.setBackground(new java.awt.Color(255, 255, 255));
        jlbKhoiHanh.setForeground(new java.awt.Color(255, 51, 51));
        jlbKhoiHanh.setText("a");

        jLabel20.setText("Định dạng: hh:mm");

        btnXacNhanChuyen.setBackground(new java.awt.Color(255, 255, 255));
        btnXacNhanChuyen.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnXacNhanChuyen.setText("XÁC NHẬN");
        btnXacNhanChuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanChuyenActionPerformed(evt);
            }
        });

        jLabel22.setBackground(new java.awt.Color(204, 204, 204));
        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel22.setText("TRẠNG THÁI:");

        jtfTGKhoiHanh.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        cbbThoiGian.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbbThoiGian.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbbTrangThai.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbbTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đi", "Về" }));

        jLabel21.setBackground(new java.awt.Color(204, 204, 204));
        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel21.setText("TG ĐẾN:");

        jtfTGDen.setEditable(false);
        jtfTGDen.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfTGDen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfTGDenActionPerformed(evt);
            }
        });

        jLabel23.setText("Định dạng: hh:mm");

        jlbMaChuyen.setBackground(new java.awt.Color(255, 255, 255));
        jlbMaChuyen.setForeground(new java.awt.Color(255, 51, 51));
        jlbMaChuyen.setText("a");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbTenDialogChuyen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnXacNhanChuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbKhoiHanh, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jlbMaChuyen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlbMaTuyen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtfMaChuyen, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jtfMaTuyen, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jtfTGKhoiHanh, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cbbThoiGian, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbbTrangThai, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtfTGDen, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jlbTenDialogChuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jtfMaChuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbMaChuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfMaTuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(2, 2, 2)
                .addComponent(jlbMaTuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cbbThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jLabel20)
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jtfTGKhoiHanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jlbKhoiHanh, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfTGDen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addComponent(btnXacNhanChuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout jdlThongTinChuyenLayout = new javax.swing.GroupLayout(jdlThongTinChuyen.getContentPane());
        jdlThongTinChuyen.getContentPane().setLayout(jdlThongTinChuyenLayout);
        jdlThongTinChuyenLayout.setHorizontalGroup(
            jdlThongTinChuyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jdlThongTinChuyenLayout.setVerticalGroup(
            jdlThongTinChuyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel2.setText("jLabel2");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THÔNG TIN BẢNG CHUYẾN");

        jtbChuyen.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtbChuyen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MÃ CHUYẾN", "MÃ TUYẾN", "THỜI GIAN HOẠT ĐỘNG", "THỜI GIAN KHỞI HÀNH", "THỜI GIAN KẾT THÚC", "TRẠNG THÁI"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbChuyen.setGridColor(new java.awt.Color(255, 255, 255));
        jtbChuyen.setRowHeight(25);
        jtbChuyen.setSelectionBackground(new java.awt.Color(51, 204, 255));
        jtbChuyen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbChuyenMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtbChuyenMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jtbChuyen);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Chức năng");

        btnThem.setBackground(new java.awt.Color(255, 255, 255));
        btnThem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnThem.setText("THÊM");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(255, 255, 255));
        btnSua.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSua.setText("SỬA");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(255, 255, 255));
        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnXoa.setText("XÓA");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Tìm kiếm:");

        jtfTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfTimKiemKeyReleased(evt);
            }
        });

        cbbTiemKiem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        cbbSapXep.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbbSapXep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbSapXepActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Sắp xếp:");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/outline_arrow_back_black_24dp_1.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnThongTIn.setBackground(new java.awt.Color(255, 255, 255));
        btnThongTIn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnThongTIn.setText("THÔNG TIN");
        btnThongTIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongTInActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(227, 227, 227)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator2)
                            .addComponent(jSeparator1)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(59, 59, 59)
                                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(74, 74, 74)
                                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtfTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbbTiemKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel9)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbbSapXep, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnThongTIn, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(0, 42, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1)
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThongTIn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbSapXep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jtfTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(cbbTiemKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        jTabbedPane2.addTab("CHUYẾN", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("THÔNG TIN KHOẢNG THỜI GIAN HOẠT ĐỘNG");

        jtbThoiGianHoatDong.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtbThoiGianHoatDong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MÃ THỜI GIAN HĐ", "TÊN THỜI GIAN HĐ", "NGÀY BẮT ĐẦU", "NGÀY KẾT THÚC"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbThoiGianHoatDong.setGridColor(new java.awt.Color(255, 255, 255));
        jtbThoiGianHoatDong.setRowHeight(25);
        jtbThoiGianHoatDong.setSelectionBackground(new java.awt.Color(51, 204, 255));
        jtbThoiGianHoatDong.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtbThoiGianHoatDong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbThoiGianHoatDongMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtbThoiGianHoatDongMousePressed(evt);
            }
        });
        jScrollPane4.setViewportView(jtbThoiGianHoatDong);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Chức năng");

        btnThem1.setBackground(new java.awt.Color(255, 255, 255));
        btnThem1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnThem1.setText("THÊM");
        btnThem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem1ActionPerformed(evt);
            }
        });

        btnSua1.setBackground(new java.awt.Color(255, 255, 255));
        btnSua1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSua1.setText("SỬA");
        btnSua1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSua1ActionPerformed(evt);
            }
        });

        btnXoa1.setBackground(new java.awt.Color(255, 255, 255));
        btnXoa1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnXoa1.setText("XÓA");
        btnXoa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa1ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Tìm kiếm:");

        jtfTimKiem1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfTimKiem1KeyReleased(evt);
            }
        });

        cbbTiemKiem1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbbTiemKiem1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TÊN", "NGÀY BẮT ĐẦU", "NGÀY KẾT THÚC" }));

        cbbSapXep1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbbSapXep1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TÊN TĂNG", "TÊN GIẢM", "NGÀY BĐ TĂNG" }));
        cbbSapXep1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbSapXep1ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Sắp xếp:");

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/outline_arrow_back_black_24dp_1.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        btnThongTIn1.setBackground(new java.awt.Color(255, 255, 255));
        btnThongTIn1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnThongTIn1.setText("THÔNG TIN");
        btnThongTIn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongTIn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addGap(182, 182, 182)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator6)
                            .addComponent(jSeparator5)
                            .addComponent(jScrollPane4)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addGap(59, 59, 59)
                                        .addComponent(btnThem1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(74, 74, 74)
                                        .addComponent(btnSua1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                                        .addComponent(btnXoa1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtfTimKiem1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbbTiemKiem1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel16)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbbSapXep1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnThongTIn1, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(0, 42, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel13)
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton5)
                        .addGap(18, 18, 18)))
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(btnThem1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThongTIn1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbSapXep1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jtfTimKiem1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(cbbTiemKiem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        jTabbedPane2.addTab("KHOẢNG THỜI GIAN", jPanel5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtbChuyenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbChuyenMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jtbChuyenMouseClicked

    private void jtbChuyenMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbChuyenMousePressed
        // TODO add your handling code here:
//        hangDangChon = jtbChuyen.getSelectedRow();
//        if (hangDangChon != -1) {
//            if (evt.getButton() == MouseEvent.BUTTON3) {
//                hienThiDialog("THÔNG TIN TUYẾN");
//            }
//        }
    }//GEN-LAST:event_jtbChuyenMousePressed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
//        hienThiDialog("THÊM TUYẾN");
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
//        if (hangDangChon < 0) {
//            JOptionPane.showMessageDialog(this, "Bạn chưa chọn đối tượng! Vui lòng chọn 1 dòng trong bảng");
//        } else {
//            hienThiDialog("SỬA TUYẾN");
//        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
//        if (hangDangChon < 0) {
//            JOptionPane.showMessageDialog(this, "Bạn chưa chọn đối tượng! Vui lòng chọn 1 hàng trong bảng");
//
//        } else {
//            int input = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa không?", "Cảnh báo", JOptionPane.YES_NO_OPTION);
//            if (input == JOptionPane.YES_OPTION) {
//                String maTuyen = jtbChuyen.getValueAt(hangDangChon, 0).toString();
//                boolean kt = tuyenDao.xoaTuyenTrongDB(maTuyen);
//                if (kt) {
//                    tuyenDao.xoaTramKhoiBang(hangDangChon, tbmBangTuyen);
//                    hangDangChon = -1;
//                    jtbChuyen.clearSelection();
//                } else {
//                    JOptionPane.showMessageDialog(this, "Không thể xóa vì có tàu đang chạy trên tuyến này");
//                }
//            }
//        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void jtfTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfTimKiemKeyReleased
        // TODO add your handling code here:

//        if (cbbTiemKiem.getSelectedIndex() == 0) {// tim kiem theo ma tuyen
//            String maTuyen = jtfTimKiem.getText().trim();
//            tuyenDao.loadDSTuyenVaoBang(LopKetNoi.select("select * from tuyen where maTuyen like ?",
//                "%" + maTuyen + "%"), tbmBangTuyen);
//        } else {// tim kiem theo ten tuyen
//            String tenTuyen = jtfTimKiem.getText().trim();
//            tuyenDao.loadDSTuyenVaoBang(LopKetNoi.select("select * from tuyen where tenTuyen like ?",
//                "%" + tenTuyen + "%"), tbmBangTuyen);
//        }
    }//GEN-LAST:event_jtfTimKiemKeyReleased

    private void cbbSapXepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbSapXepActionPerformed
        // TODO add your handling code here:
//        if (cbbSapXep.getSelectedIndex() == 0) {// sap xep ten tuyen tu a - z
//            tuyenDao.loadDSTuyenVaoBang(LopKetNoi.select("select * from tuyen order by tentuyen ASC"), tbmBangTuyen);
//        } else {
//            tuyenDao.loadDSTuyenVaoBang(LopKetNoi.select("select * from tuyen order by tentuyen DESC"), tbmBangTuyen);
//        }
    }//GEN-LAST:event_cbbSapXepActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new ChuyenManHinhView(this, new JPanelQuanLiLoTrinh()).change();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnThongTInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongTInActionPerformed
        // TODO add your handling code here:
        if (hangThoiGian == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn 1 hàng trong bảng");
        } else
            hienThiDialogThoiGian(thongTin);
    }//GEN-LAST:event_btnThongTInActionPerformed

    private void jtbThoiGianHoatDongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbThoiGianHoatDongMouseClicked
        // TODO add your handling code here:
        hangThoiGian = jtbThoiGianHoatDong.getSelectedRow();
    }//GEN-LAST:event_jtbThoiGianHoatDongMouseClicked

    private void jtbThoiGianHoatDongMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbThoiGianHoatDongMousePressed
        // TODO add your handling code here:
        hangThoiGian = jtbThoiGianHoatDong.getSelectedRow();

    }//GEN-LAST:event_jtbThoiGianHoatDongMousePressed

    private void btnThem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThem1ActionPerformed
        hienThiDialogThoiGian(them);
    }//GEN-LAST:event_btnThem1ActionPerformed

    private void btnSua1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSua1ActionPerformed
        // TODO add your handling code here:
        if (hangThoiGian < 0) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn đối tượng! Vui lòng chọn 1 dòng trong bảng");
        } else {
            hienThiDialogThoiGian(sua);
        }
    }//GEN-LAST:event_btnSua1ActionPerformed

    private void btnXoa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoa1ActionPerformed
        // TODO add your handling code here:
        if (hangThoiGian < 0) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn đối tượng! Vui lòng chọn 1 hàng trong bảng");
        } else {
            int xacNhan = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa không?", "Cảnh báo", JOptionPane.YES_NO_OPTION);
            if (xacNhan == JOptionPane.YES_OPTION) {
                if (xoaThoiGian()) {
                    JOptionPane.showMessageDialog(this, "Xóa thành công!");
                    hangThoiGian = -1;
                } else {
                    JOptionPane.showMessageDialog(this, "Xóa thất bại!");
                }

            }
        }

    }//GEN-LAST:event_btnXoa1ActionPerformed

    private void jtfTimKiem1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfTimKiem1KeyReleased
        // TODO add your handling code here:

//        if (cbbTiemKiem.getSelectedIndex() == 0) {// tim kiem theo ma tuyen
//            String maTuyen = jtfTimKiem.getText().trim();
//            tuyenDao.loadDSTuyenVaoBang(LopKetNoi.select("select * from tuyen where maTuyen like ?",
//                "%" + maTuyen + "%"), tbmBangTuyen);
//        } else {// tim kiem theo ten tuyen
//            String tenTuyen = jtfTimKiem.getText().trim();
//            tuyenDao.loadDSTuyenVaoBang(LopKetNoi.select("select * from tuyen where tenTuyen like ?",
//                "%" + tenTuyen + "%"), tbmBangTuyen);
//        }
    }//GEN-LAST:event_jtfTimKiem1KeyReleased

    private void cbbSapXep1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbSapXep1ActionPerformed
        // TODO add your handling code here:
//        if (cbbSapXep.getSelectedIndex() == 0) {// sap xep ten tuyen tu a - z
//            tuyenDao.loadDSTuyenVaoBang(LopKetNoi.select("select * from tuyen order by tentuyen ASC"), tbmBangTuyen);
//        } else {
//            tuyenDao.loadDSTuyenVaoBang(LopKetNoi.select("select * from tuyen order by tentuyen DESC"), tbmBangTuyen);
//        }
    }//GEN-LAST:event_cbbSapXep1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        new ChuyenManHinhView(this, new JPanelQuanLiLoTrinh()).change();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnThongTIn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongTIn1ActionPerformed
        // TODO add your handling code here:
        if (hangThoiGian == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn 1 hàng trong bảng");
        } else
            hienThiDialogThoiGian(thongTin);
    }//GEN-LAST:event_btnThongTIn1ActionPerformed

    private void btnXacNhanThoiGianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanThoiGianActionPerformed
        // TODO add your handling code here:
        String loai = jlbTenDialog.getText();
        xuLiXacNhanThoiGian(loai);
    }//GEN-LAST:event_btnXacNhanThoiGianActionPerformed

    private void btnXacNhanChuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanChuyenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXacNhanChuyenActionPerformed

    private void jtfTGDenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfTGDenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfTGDenActionPerformed

    //==============================================================================================
    private void kiemTraMaThoiGian() {
        String maThoiGian;
        if (jtfMaThoiGian.getText().equals("")) {
            jlbMaThoiGian.setText("Không được để trống");
        } else {
            maThoiGian = jtfMaThoiGian.getText().trim();
            boolean kiemTra = StringDungChung.kiemTraChuoiKhongCach(maThoiGian);
            if (kiemTra) {// khi chuỗi không cách
                boolean kiemTraMaTrung = thoiGianDao.kiemTraMaTrung(maThoiGian);
                if (kiemTraMaTrung) {
                    jlbMaThoiGian.setText(" ");
                } else {
                    jlbMaThoiGian.setText("Mã bị trùng");
                }
            } else {// chuỗi có cách
                jlbMaThoiGian.setText("Mã không được chứa khoảng trắng");
            }
        }
    }

    private void kiemTraNgayBatDau() {
        Date ngayBD = null;
        try {
            ngayBD = jdcNgayBatDau.getDate();
            String s = StringDungChung.DateSangString(ngayBD, "dd/MM/yyyy");
            jlbNgayBatDau.setText(" ");
            kiemTraNgayKetThuc();
        } catch (Exception e) {
            jlbNgayBatDau.setText("Không đúng định dạng");
        }
    }

    private void kiemTraNgayKetThuc() {
        Date ngayKT = null;
        try {
            ngayKT = jdcNgayKetThuc.getDate();
            String s = StringDungChung.DateSangString(ngayKT, "dd/MM/yyyy");
            if (jlbNgayBatDau.getText().equals(" ")) {// nếu ngày BD hợp lệ thì kiểm tra chúng có từ nhỏ đến lớn không
                Date ngayBD = jdcNgayBatDau.getDate();
                if (ngayBD.compareTo(ngayKT) <= 0) {
                    jlbNgayKetThuc.setText(" ");
                } else {
                    jlbNgayKetThuc.setText("Ngày kết thúc phải lớn hơn ngày bắt đầu");
                }
            }
        } catch (Exception e) {
            jlbNgayKetThuc.setText("Không đúng định dạng");
        }
    }

    private boolean kiemTraDuLieuHopLe() {
        // mã không cách và không được trùng
        kiemTraMaThoiGian();
        kiemTraNgayBatDau();
        kiemTraNgayKetThuc();
        if (jlbMaThoiGian.getText().equals(" ") && jlbNgayBatDau.getText().equals(" ") && jlbNgayKetThuc.getText().equals(" ")) {
            Date ngayBD = jdcNgayBatDau.getDate();
            Date ngayKT = jdcNgayKetThuc.getDate();
            boolean kiemTra = thoiGianDao.kiemTraNgayBatDauVaKetThuc(ngayBD, ngayKT); // cos bij chong len nahu khong
            kiemTra = true;
            if (kiemTra) {
                return true;
            } else {
                JOptionPane.showMessageDialog(jdlThongTinThoiGian, "Ngày bắt đầu và kết thúc không được "
                        + "chồng lên dữ liệu đã có");
                return false;
            }
        } else {
            return false;
        }
    }

    private ThoiGianHoatDong getTGHDTuJDL() {
        String maThoiGian = jtfMaThoiGian.getText().trim();
        String tenThoiGian = jtfTenThoiGian.getText().trim();
//        String ngayBD = StringDungChung.DateSangString(jdcNgayBatDau.getDate(), "dd/MM/yyyy");
//        String ngayKT = StringDungChung.DateSangString(jdcNgayKetThuc.getDate(), "dd/MM/yyyy")
        Date ngayBD = jdcNgayBatDau.getDate();
        Date ngayKT = jdcNgayKetThuc.getDate();
        ThoiGianHoatDong TGHD = new ThoiGianHoatDong(maThoiGian, tenThoiGian, ngayBD, ngayKT);
        return TGHD;

    }

    private boolean themThoiGian() {
        if (kiemTraDuLieuHopLe()) {
            ThoiGianHoatDong TGHD = getTGHDTuJDL();
            thoiGianDao.themThoiGianVaoDB(TGHD);
            thoiGianDao.themThoiGianVaoBang(TGHD, jtbThoiGianHoatDong);
        } else {
            System.out.println("kiem tra them that bai");
            return false;
        }
        return true;
    }

    private boolean suaThoiGian() {
        ThoiGianHoatDong TGHD = getTGHDTuJDL();

        thoiGianDao.xoaThoiGianTrongDB(TGHD.getMaThoiGianHoatDong());
        if (thoiGianDao.themThoiGianVaoDB(TGHD)) {
            thoiGianDao.suaThoiGianTrongBang(TGHD, hangThoiGian, jtbThoiGianHoatDong);
            return true;
        } else {
            return false;
        }
    }

    private boolean xoaThoiGian() {
        if (thoiGianDao.xoaThoiGianTrongDB(jtbThoiGianHoatDong.getValueAt(hangThoiGian, 0).toString())) {
            thoiGianDao.xoaThoiGianKhoiBang(hangThoiGian, tbmThoiGian);
            return true;
        } else {
            return false;
        }

    }

    private void setTatCaTruongRong() {
        SimpleDateFormat formater = new SimpleDateFormat("dd/MM/yyyy");
        String ngayHienTai = formater.format(new Date());
        Date ngayHienTaiDate = StringDungChung.StringSangDate(ngayHienTai, "dd/MM/yyyy");
        jtfMaThoiGian.setText("");
        jtfTenThoiGian.setText("");
        jdcNgayBatDau.setDate(ngayHienTaiDate);
        jdcNgayKetThuc.setDate(ngayHienTaiDate);
    }

    private void setTatCaCacThongBaoRong() {
        jlbMaThoiGian.setText(" ");
        jlbTenThoiGian.setText(" ");
        jlbNgayBatDau.setText(" ");
        jlbNgayKetThuc.setText(" ");
    }

    private void batTatCaTruong() {
        jtfMaThoiGian.setEditable(true);
        jtfTenThoiGian.setEditable(true);
        jdcNgayBatDau.setEnabled(true);
        jdcNgayKetThuc.setEnabled(true);
    }

    private void tatTatCaTruong() {
        jtfMaThoiGian.setEditable(false);
        jtfTenThoiGian.setEditable(false);
        jdcNgayBatDau.setEnabled(false);
        jdcNgayKetThuc.setEnabled(false);
    }

    private void hienThiDialogThoiGian(String loai) {
        setTatCaCacThongBaoRong();
        batTatCaTruong();
        if (loai.equals(thongTin)) {
            thoiGianDao.getTuyenTuBang(hangThoiGian, jtbThoiGianHoatDong, jtfMaThoiGian,
                    jtfTenThoiGian, jdcNgayBatDau, jdcNgayKetThuc);
        } else if (loai.equals(them)) {
            setTatCaTruongRong();
        } else if (loai.equals(sua)) {
            jtfMaThoiGian.setEditable(false);
            thoiGianDao.getTuyenTuBang(hangThoiGian, jtbThoiGianHoatDong, jtfMaThoiGian,
                    jtfTenThoiGian, jdcNgayBatDau, jdcNgayKetThuc);
        }
        jlbTenDialog.setText(loai);
        jdlThongTinThoiGian.setLocationRelativeTo(this);
        jdlThongTinThoiGian.setVisible(true);
    }

    private void xuLiXacNhanThoiGian(String loai) {
        if (loai.equals(thongTin)) {
            jdlThongTinThoiGian.dispose();
        } else if (loai.equals(them)) {
            if (themThoiGian()) {
                setTatCaTruongRong();
                setTatCaCacThongBaoRong();
                hangThoiGian = jtbThoiGianHoatDong.getRowCount() - 1;
            } else {
                JOptionPane.showMessageDialog(jdlThongTinThoiGian, "Thêm thất bại");
            }
        } else if (loai.equals(sua)) {
            if (suaThoiGian()) {
                jdlThongTinThoiGian.dispose();
            } else {
                JOptionPane.showMessageDialog(jdlThongTinThoiGian, "Sửa thất bại");
            }
        }
    }

    //CHUYEN
//===============================================================================================
    private boolean kiemTraDuLieuHopLeChuyen() {
        // mã không cách và không được trùng
//        kiemTraMaThoiGian();
//        kiemTraNgayBatDau();
//        kiemTraNgayKetThuc();
//        if (jlbMaThoiGian.getText().equals(" ") && jlbNgayBatDau.getText().equals(" ") && jlbNgayKetThuc.getText().equals(" ")) {
//            Date ngayBD = jdcNgayBatDau.getDate();
//            Date ngayKT = jdcNgayKetThuc.getDate();
//            boolean kiemTra = thoiGianDao.kiemTraNgayBatDauVaKetThuc(ngayBD, ngayKT); // cos bij chong len nahu khong
//            kiemTra=true;
//            if (kiemTra) {
//                return true;
//            } else {
//                JOptionPane.showMessageDialog(jdlThongTinThoiGian, "Ngày bắt đầu và kết thúc không được "
//                        + "chồng lên dữ liệu đã có");
//                return false;
//            }
//        } else {
//            return false;
//        }
        return true;
    }

    private void loadThoiGianVaoCBB(ResultSet rs, JComboBox cbb) {
        cbb.removeAllItems();
        try {
            while (rs.next()) {
                String ngayBD = StringDungChung.DateSangString(rs.getDate(1), "dd/MM/yyyy");
                String ngayKT = StringDungChung.DateSangString(rs.getDate(2), "dd/MM/yyyy");
                String tam = ngayBD + " đến " + ngayKT;
                cbb.addItem(tam);
            }
        } catch (Exception e) {
        }
    }


   

 
    private Chuyen getChuyenTuJDL() {
        String maChuyen = jtfMaChuyen.getText().trim();
        String maTuyen = jtfMaTuyen.getText().trim();
        String khoangThoiGian = cbbThoiGian.getSelectedItem().toString() ;//        String ngayBD = StringDungChung.DateSangString(jdcNgayBatDau.getDate(), "dd/MM/yyyy");
                //        String ngayKT = StringDungChung.DateSangString(jdcNgayKetThuc.getDate(), "dd/MM/yyyy")
        LocalTime tgKhoiHanh = (LocalTime) DateTimeFormatter.ofPattern("hh:mm").parse(jtfTGKhoiHanh.getText().trim());
        LocalTime tgKetThuc = ChuyenDao.getThoiGianKT(maTuyen, tgKhoiHanh, 60f);
        String trangThai = cbbTrangThai.getSelectedItem().toString();
        Chuyen chuyen = new Chuyen(maChuyen, maTuyen, khoangThoiGian, tgKhoiHanh, tgKetThuc, trangThai);
        return chuyen;

    }

    private boolean themChuyen() {
        if (kiemTraDuLieuHopLe()) {
            Chuyen chuyen = getChuyenTuJDL();
            ChuyenDao.themChuyenVaoDB(chuyen);
            ChuyenDao.themChuyenVaoBang(chuyen, jtbChuyen);
        } else {
            System.out.println("kiem tra them that bai");
            return false;
        }
        return true;
    }

    private boolean suaChuyen() {
        Chuyen chuyen = getChuyenTuJDL();
       ChuyenDao.xoaChuyenTrongDB(chuyen.getMa());
        if (ChuyenDao.themChuyenVaoDB(chuyen)) {
           ChuyenDao.suaChuyenTrongBang(chuyen, hangChuyen, jtbChuyen);
            return true;
        } else {
            return false;
        }
    }

    private boolean xoaChuyen() {
        if (ChuyenDao.xoaChuyenTrongDB(jtbChuyen.getValueAt(hangThoiGian, 0).toString())) {
            ChuyenDao.xoaChuyenKhoiBang(hangChuyen, tbmChuyen);
            return true;
        } else {
            return false;
        }

    }

    
    private void setTatCaTruongRongChuyen() {
        jtfMaTuyen.setText("");
        jtfMaTuyen.setText("");
        cbbThoiGian.setSelectedIndex(0);
        jtfTGKhoiHanh.setText("");
        jtfTGDen.setText("");
        cbbTrangThai.setSelectedIndex(0);
    }

    private void setTatCaCacThongBaoRongChuyen() {
        jlbMaChuyen.setText(" ");
        jlbMaTuyen.setText(" ");
        jlbKhoiHanh.setText(" ");
    }

    private void batTatCaTruongChuyen() {
        jtfMaChuyen.setEditable(true);
        jtfMaTuyen.setEditable(true);
        cbbThoiGian.setEnabled(true);
        jtfTGKhoiHanh.setEnabled(true);
        cbbTrangThai.setEnabled(true);
    }

    private void tatTatCaTruongChuyen() {
      jtfMaChuyen.setEditable(false);
        jtfMaTuyen.setEditable(false);
        cbbThoiGian.setEnabled(false);
        jtfTGKhoiHanh.setEnabled(false);
        cbbTrangThai.setEnabled(false);
    }

    private void hienThiDialogChuyen(String loai) {
        setTatCaCacThongBaoRongChuyen();
        batTatCaTruongChuyen();
        if (loai.equals(thongTin)) {
            ChuyenDao.getChuyenTuBang(hangChuyen, jtbChuyen, jtfMaChuyen,
                    jtfMaTuyen, cbbThoiGian, jtfTGKhoiHanh, jtfTGDen, cbbTrangThai);
        } else if (loai.equals(them)) {
            setTatCaTruongRongChuyen();
        } else if (loai.equals(sua)) {
            jtfMaChuyen.setEditable(false);
            ChuyenDao.getChuyenTuBang(hangChuyen, jtbChuyen, jtfMaChuyen,
                    jtfMaTuyen, cbbThoiGian, jtfTGKhoiHanh, jtfTGDen, cbbTrangThai);
        }
        jlbTenDialogChuyen.setText(loai);
        jdlThongTinChuyen .setLocationRelativeTo(this);
        jdlThongTinChuyen.setVisible(true);
    }

    private void xuLiXacNhanThoiGianChuyen(String loai) {
        if (loai.equals(thongTin)) {
            jdlThongTinChuyen.dispose();
        } else if (loai.equals(them)) {
            if (themChuyen()) {
                setTatCaTruongRongChuyen();
                setTatCaCacThongBaoRongChuyen();
                hangChuyen = jtbChuyen.getRowCount() - 1;
            } else {
                JOptionPane.showMessageDialog(jdlThongTinChuyen, "Thêm thất bại");
            }
        } else if (loai.equals(sua)) {
            if (suaChuyen()) {
                jdlThongTinChuyen.dispose();
            } else {
                JOptionPane.showMessageDialog(jdlThongTinChuyen, "Sửa thất bại");
            }
        }
    }
//============================================================================================
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnSua1;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThem1;
    private javax.swing.JButton btnThongTIn;
    private javax.swing.JButton btnThongTIn1;
    private javax.swing.JButton btnXacNhanChuyen;
    private javax.swing.JButton btnXacNhanThoiGian;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoa1;
    private javax.swing.JComboBox<String> cbbSapXep;
    private javax.swing.JComboBox<String> cbbSapXep1;
    private javax.swing.JComboBox<String> cbbThoiGian;
    private javax.swing.JComboBox<String> cbbTiemKiem;
    private javax.swing.JComboBox<String> cbbTiemKiem1;
    private javax.swing.JComboBox<String> cbbTrangThai;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTabbedPane jTabbedPane2;
    private com.toedter.calendar.JDateChooser jdcNgayBatDau;
    private com.toedter.calendar.JDateChooser jdcNgayKetThuc;
    private javax.swing.JDialog jdlThongTinChuyen;
    private javax.swing.JDialog jdlThongTinThoiGian;
    private javax.swing.JLabel jlbKhoiHanh;
    private javax.swing.JLabel jlbMaChuyen;
    private javax.swing.JLabel jlbMaThoiGian;
    private javax.swing.JLabel jlbMaTuyen;
    private javax.swing.JLabel jlbNgayBatDau;
    private javax.swing.JLabel jlbNgayKetThuc;
    private javax.swing.JLabel jlbTenDialog;
    private javax.swing.JLabel jlbTenDialogChuyen;
    private javax.swing.JLabel jlbTenThoiGian;
    private javax.swing.JTable jtbChuyen;
    private javax.swing.JTable jtbThoiGianHoatDong;
    private javax.swing.JTextField jtfMaChuyen;
    private javax.swing.JTextField jtfMaThoiGian;
    private javax.swing.JTextField jtfMaTuyen;
    private javax.swing.JTextField jtfTGDen;
    private javax.swing.JTextField jtfTGKhoiHanh;
    private javax.swing.JTextField jtfTenThoiGian;
    private javax.swing.JTextField jtfTimKiem;
    private javax.swing.JTextField jtfTimKiem1;
    // End of variables declaration//GEN-END:variables
}
