/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.quanlituyen;

import connectSQL.LopKetNoi;
import controller.ChuyenManHinhView;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import view.JPanelQuanLiTuyen;
import java.sql.PreparedStatement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import module.Tram;
import moduledao.TramDao;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class JPanelDanhSachTram extends javax.swing.JPanel {

    private TramDao tramDao = new TramDao();
    private LopKetNoi lopKetNoi = new LopKetNoi();
    private DefaultTableModel tbmBangTram;
    private int hangDangChon = -1;

    /**
     * Creates new form JPanelDanhSachTram
     */
    public JPanelDanhSachTram() {
        initComponents();
//        disableJTF();
        jtbDanhSachTram.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tbmBangTram = (DefaultTableModel) jtbDanhSachTram.getModel();
        tramDao.loadDSTramVaoBang(LopKetNoi.select("select * from Tram"), tbmBangTram);

    }

    private void enableJTF() {
        jtfTenTram.enable(true);
        jtfDiaChi.enable(true);
    }

    private void disableJTF() {
        jtfTenTram.enable(false);
        jtfDiaChi.enable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdlThemSuaTram = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jlbTenDialog = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jlbTenTramDialog = new javax.swing.JLabel();
        jtfTenTramDialog = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtfDiaChiDialog = new javax.swing.JTextField();
        btnXacNhanDialog = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jtfTenTram = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtfDiaChi = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbDanhSachTram = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jtfTimKiem = new javax.swing.JTextField();
        cbbTimKiem = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cbbSapXep = new javax.swing.JComboBox<>();

        jdlThemSuaTram.setMinimumSize(new java.awt.Dimension(420, 350));

        jPanel5.setMinimumSize(new java.awt.Dimension(397, 300));

        jlbTenDialog.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlbTenDialog.setForeground(new java.awt.Color(51, 51, 255));
        jlbTenDialog.setText("THÊM TRẠM");

        jLabel8.setText("Tên trạm:");

        jlbTenTramDialog.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jlbTenTramDialog.setForeground(new java.awt.Color(255, 51, 51));
        jlbTenTramDialog.setText("Tên trạm không được trống");

        jtfTenTramDialog.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfTenTramDialogKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfTenTramDialogKeyReleased(evt);
            }
        });

        jLabel9.setText("Địa chỉ:");

        jtfDiaChiDialog.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfDiaChiDialogKeyPressed(evt);
            }
        });

        btnXacNhanDialog.setText("XÁC NHẬN");
        btnXacNhanDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanDialogActionPerformed(evt);
            }
        });
        btnXacNhanDialog.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnXacNhanDialogKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbTenDialog)
                .addGap(156, 156, 156))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfTenTramDialog)
                            .addComponent(jtfDiaChiDialog)
                            .addComponent(jlbTenTramDialog, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(btnXacNhanDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbTenDialog)
                .addGap(50, 50, 50)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jtfTenTramDialog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbTenTramDialog)
                .addGap(22, 22, 22)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jtfDiaChiDialog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(btnXacNhanDialog)
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout jdlThemSuaTramLayout = new javax.swing.GroupLayout(jdlThemSuaTram.getContentPane());
        jdlThemSuaTram.getContentPane().setLayout(jdlThemSuaTramLayout);
        jdlThemSuaTramLayout.setHorizontalGroup(
            jdlThemSuaTramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jdlThemSuaTramLayout.setVerticalGroup(
            jdlThemSuaTramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("DANH SÁCH TRẠM");

        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setText("Tên trạm:");

        jtfTenTram.setEditable(false);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Điền thông tin");

        jLabel5.setText("Địa chỉ:");

        jtfDiaChi.setEditable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtfTenTram, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jtfDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(320, 320, 320))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfTenTram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(jtfDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jButton2.setBackground(new java.awt.Color(153, 153, 255));
        jButton2.setText("Chức năng");

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(91, 91, 91)
                .addComponent(btnThem)
                .addGap(57, 57, 57)
                .addComponent(btnSua)
                .addGap(58, 58, 58)
                .addComponent(btnXoa)
                .addContainerGap(277, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(btnXoa))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jtbDanhSachTram.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jtbDanhSachTram.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên trạm", "Địa chỉ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbDanhSachTram.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtbDanhSachTramMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(jtbDanhSachTram);

        jLabel6.setText("Tìm kiếm:");

        jtfTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfTimKiemKeyReleased(evt);
            }
        });

        cbbTimKiem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tên trạm", "Địa chỉ" }));

        jLabel7.setText("Sắp xếp:");

        cbbSapXep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tên trạm a-z", "Tên trạm z-a" }));
        cbbSapXep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbSapXepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbbTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jtfTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbbSapXep, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(249, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(cbbTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(cbbSapXep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(263, 263, 263)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new ChuyenManHinhView(this, new JPanelQuanLiTuyen()).change();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbbSapXepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbSapXepActionPerformed
        // TODO add your handling code here:
        tbmBangTram.setRowCount(0);
        if (cbbSapXep.getSelectedIndex() == 0)// ten tram a-z
        {
            try {
                tramDao.loadDSTramVaoBang(LopKetNoi.select("select * from tram order by tenTram ASC"), tbmBangTram);
            } catch (Exception e) {
            }
        } else {// ten tram z-a
            try {
                tramDao.loadDSTramVaoBang(LopKetNoi.select("select * from tram order by tenTram DESC"), tbmBangTram);
            } catch (Exception e) {
            }
        }
        hangDangChon = -1;
        setRong();
    }//GEN-LAST:event_cbbSapXepActionPerformed

    private void jtfTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfTimKiemKeyReleased
        // TODO add your handling code here:
        if (cbbTimKiem.getSelectedIndex() == 0) {// tim kiem theo ten trạm
            try {
                // tim kiem theo ma ca tram bd va kt
                String tenTram = jtfTimKiem.getText().trim().toUpperCase();
                tramDao.loadDSTramVaoBang(LopKetNoi.select("select * from tram where tenTram like ?","%" + tenTram +"%" ), tbmBangTram);
            } catch (Exception ex) {
                Logger.getLogger(JPanelDanhSachTram.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            try {
                // tim kiem theo ma ca tram bd va kt
                String diaChi = jtfTimKiem.getText().trim();
                tramDao.loadDSTramVaoBang(LopKetNoi.select("select * from tram where diaChi like ?","%" + diaChi +"%" ), tbmBangTram);
            } catch (Exception ex) {
                Logger.getLogger(JPanelDanhSachTram.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        hangDangChon = -1;
        setRong();
    }//GEN-LAST:event_jtfTimKiemKeyReleased

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        if (hangDangChon == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn 1 dòng để xóa");
        } else {
            xoaTram();
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // kiem tra cac rang buoc
        hienThiDialog("THÊM TRẠM");
    }//GEN-LAST:event_btnThemActionPerformed

    private void hienThiDialog(String title) {
        jdlThemSuaTram.setLocationRelativeTo(this);
        jdlThemSuaTram.setVisible(true);
        jdlThemSuaTram.setTitle(title);
        jlbTenDialog.setText(title);
        if (title.equals("THÊM TRẠM")) {
            jtfTenTramDialog.enable(true);
            jtfDiaChiDialog.enable(true);
            jtfTenTramDialog.setText("");
            jtfDiaChiDialog.setText("");
        } else {
            jtfTenTramDialog.setText(jtfTenTram.getText());
            jtfDiaChiDialog.setText(jtfDiaChi.getText());
            jtfTenTramDialog.enable(false);
            jtfDiaChiDialog.enable(true);
        }
    }
    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        // kiem tra rang buoc
        if (hangDangChon == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn 1 dòng muốn sửa");
        } else
            hienThiDialog("SỬA TÀU");
    }//GEN-LAST:event_btnSuaActionPerformed

    private void jtbDanhSachTramMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbDanhSachTramMousePressed
        // TODO add your handling code here:
        hangDangChon = jtbDanhSachTram.getSelectedRow();
        tramDao.getTramTuBang(hangDangChon, jtbDanhSachTram, jtfTenTram, jtfDiaChi);
    }//GEN-LAST:event_jtbDanhSachTramMousePressed

    private void setRong(){
        jtfTenTram.setText("");
        jtfDiaChi.setText("");
    }
    private void capNhatSauKhiThem() {
        jtfTenTram.setText(jtfTenTramDialog.getText().trim().toUpperCase());
        jtfDiaChi.setText(jtfDiaChiDialog.getText().trim());
        jtfTenTramDialog.setText("");
        jtfDiaChiDialog.setText("");
        jlbTenTramDialog.setText("Tên trạm không được rỗng");
        jtfTenTramDialog.requestFocus();
    }

    private void themTram() {
        if (!jlbTenTramDialog.getText().equals(" ")) { // là bị đỏ
            JOptionPane.showMessageDialog(jdlThemSuaTram, "Thêm thất bại");
            jtfTenTramDialog.requestFocus();
            return;
        } else {
            String tenTram = jtfTenTramDialog.getText().trim().toUpperCase();
            String diaChi = jtfDiaChiDialog.getText().trim();
            //them vao csdl va bang
            Tram tram = new Tram(tenTram, diaChi);
            tramDao.themTramVaoDB(tram);
            tramDao.themTramVaoBang(tram, jtbDanhSachTram);
            JOptionPane.showMessageDialog(jdlThemSuaTram, "Thêm thành công");
            //cap nhat lai cac truong
            capNhatSauKhiThem();
            hangDangChon = jtbDanhSachTram.getRowCount() - 1;
        }
    }

    private void suaTram() {
        String tenTram = jtfTenTram.getText();
        String diaChi = jtfDiaChiDialog.getText().trim();
        //============================================================
        Tram tram = new Tram(tenTram, diaChi);
        tramDao.suaTramTrongBang(tram, hangDangChon, jtbDanhSachTram);
        tramDao.suaTramTrongDB(tram);
        //===== cap nhat lai mot so thong tin
        jtfDiaChi.setText(diaChi);
    }

    private void xoaTram() {
        int input = JOptionPane.showConfirmDialog(this, "Bạn chắn chắn muốn xóa chứ?", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (input == JOptionPane.YES_OPTION) {
            tramDao.xoaTramTrongDB(jtfTenTram.getText());
            tramDao.xoaTramKhoiBang(hangDangChon, tbmBangTram);
            //===================================
            hangDangChon = -1;
            jtfTenTram.setText("");
            jtfDiaChi.setText("");
            jtbDanhSachTram.clearSelection();
        }
    }
    private void btnXacNhanDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanDialogActionPerformed
        // TODO add your handling code here:
        if (jdlThemSuaTram.getTitle().equals("Thêm trạm")) {
            themTram();
        } else {
            suaTram();
            jdlThemSuaTram.dispose();
        }
    }//GEN-LAST:event_btnXacNhanDialogActionPerformed

    private void jtfTenTramDialogKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfTenTramDialogKeyReleased
        // TODO add your handling code here:
        String tenTram = jtfTenTramDialog.getText().toUpperCase();
        if (!tenTram.equals("")) {
            jlbTenTramDialog.setText(" ");
            try {
                ResultSet rs = LopKetNoi.select("select * from Tram where tenTram = ?", tenTram);
                if (rs.next()) {
                    jlbTenTramDialog.setText("Tên trạm bị trùng");
                } else {
                    jlbTenTramDialog.setText(" ");
                }
            } catch (Exception e) {
            }
        } else {
            jlbTenTramDialog.setText("Tên trạm không được rỗng");
        }
    }//GEN-LAST:event_jtfTenTramDialogKeyReleased

    private void jtfTenTramDialogKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfTenTramDialogKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER || evt.getKeyCode() == KeyEvent.VK_DOWN) {
            jtfDiaChiDialog.requestFocus();
        }
    }//GEN-LAST:event_jtfTenTramDialogKeyPressed

    private void jtfDiaChiDialogKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfDiaChiDialogKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER || evt.getKeyCode() == KeyEvent.VK_UP) {
            jtfTenTramDialog.requestFocus();
        }
        if (evt.getKeyCode() == KeyEvent.VK_ENTER || evt.getKeyCode() == KeyEvent.VK_DOWN) {
            btnXacNhanDialog.requestFocus();
        }
    }//GEN-LAST:event_jtfDiaChiDialogKeyPressed

    private void btnXacNhanDialogKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnXacNhanDialogKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            themTram();
        }
    }//GEN-LAST:event_btnXacNhanDialogKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXacNhanDialog;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbbSapXep;
    private javax.swing.JComboBox<String> cbbTimKiem;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JDialog jdlThemSuaTram;
    private javax.swing.JLabel jlbTenDialog;
    private javax.swing.JLabel jlbTenTramDialog;
    private javax.swing.JTable jtbDanhSachTram;
    private javax.swing.JTextField jtfDiaChi;
    private javax.swing.JTextField jtfDiaChiDialog;
    private javax.swing.JTextField jtfTenTram;
    private javax.swing.JTextField jtfTenTramDialog;
    private javax.swing.JTextField jtfTimKiem;
    // End of variables declaration//GEN-END:variables
}
