/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.quanlituyen;

import connectSQL.LopKetNoi;
import controller.ChuyenManHinhView;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import view.JPanelQuanLiTuyen;
import java.sql.PreparedStatement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import module.Tram;
import moduledao.TramDao;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class JPanelDanhSachTram extends javax.swing.JPanel {

    private TramDao tramDao = new TramDao();
    private LopKetNoi lopKetNoi = new LopKetNoi();
    private DefaultTableModel tbmBangTram;
    private int hangDangChon = -1;

    /**
     * Creates new form JPanelDanhSachTram
     */
    public JPanelDanhSachTram() {
        initComponents();
        jtbDanhSachTram.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tbmBangTram = (DefaultTableModel) jtbDanhSachTram.getModel();
        tramDao.loadDSTramVaoBang(LopKetNoi.select("select * from Tram"), tbmBangTram);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jtfTenTram = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtfDiaChi = new javax.swing.JTextField();
        jlbTenTram = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbDanhSachTram = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jtfTimKiem = new javax.swing.JTextField();
        cbbTimKiem = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cbbSapXep = new javax.swing.JComboBox<>();

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("DANH SÁCH TRẠM");

        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setText("Tên trạm:");

        jtfTenTram.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfTenTramKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfTenTramKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Điền thông tin");

        jLabel5.setText("Địa chỉ:");

        jlbTenTram.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jlbTenTram.setForeground(new java.awt.Color(255, 51, 51));
        jlbTenTram.setText("Tên trạm không được trống");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbTenTram, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jtfTenTram, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jtfDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(320, 320, 320))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfTenTram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(jtfDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbTenTram)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jButton2.setBackground(new java.awt.Color(153, 153, 255));
        jButton2.setText("Chức năng");

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(91, 91, 91)
                .addComponent(btnThem)
                .addGap(57, 57, 57)
                .addComponent(btnSua)
                .addGap(58, 58, 58)
                .addComponent(btnXoa)
                .addContainerGap(277, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(btnXoa))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jtbDanhSachTram.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jtbDanhSachTram.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên trạm", "Địa chỉ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbDanhSachTram.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtbDanhSachTramMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(jtbDanhSachTram);

        jLabel6.setText("Tìm kiếm:");

        jtfTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfTimKiemKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfTimKiemKeyReleased(evt);
            }
        });

        cbbTimKiem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tên trạm", "Địa chỉ" }));

        jLabel7.setText("Sắp xếp:");

        cbbSapXep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tên trạm a-z", "Tên trạm z-a" }));
        cbbSapXep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbSapXepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbbTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jtfTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbbSapXep, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(249, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(cbbTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(cbbSapXep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(263, 263, 263)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new ChuyenManHinhView(this, new JPanelQuanLiTuyen()).change();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbbSapXepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbSapXepActionPerformed
        // TODO add your handling code here:
        tbmBangTram.setRowCount(0);
        if (cbbSapXep.getSelectedIndex() == 0)// ten tram a-z
        {
            try {
                PreparedStatement ps = lopKetNoi.getConnection().prepareStatement("select * from tram order by tenTram  ASC");
                ResultSet rs = ps.executeQuery();
                while (rs.next()) {
                    tbmBangTram.addRow(new Object[]{rs.getString(1), rs.getString(2)});
                }
            } catch (Exception e) {
            }

        } else {// ten tram z-a
            try {
                PreparedStatement ps = lopKetNoi.getConnection().prepareStatement("select * from tram order by tenTram DESC");
                ResultSet rs = ps.executeQuery();
                while (rs.next()) {
                    tbmBangTram.addRow(new Object[]{rs.getString(1), rs.getString(2)});
                }
            } catch (Exception e) {
            }
        }
        hangDangChon = -1;
    }//GEN-LAST:event_cbbSapXepActionPerformed

    private void jtfTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfTimKiemKeyReleased
        // TODO add your handling code here:
        tbmBangTram.setRowCount(0);
        if (cbbTimKiem.getSelectedIndex() == 0) {// tim kiem theo ten trạm
            try {
                // tim kiem theo ma ca tram bd va kt
                PreparedStatement ps = lopKetNoi.getConnection().prepareStatement("select * from tram where tenTram like '%" + jtfTimKiem.getText() + "%'");
                ResultSet rs = ps.executeQuery();
                while (rs.next()) {
                    tbmBangTram.addRow(new Object[]{rs.getString(1), rs.getString(2)});
                }
            } catch (SQLException ex) {
                Logger.getLogger(JPanelDanhSachTram.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            try {
                // tim kiem theo ma ca tram bd va kt
                PreparedStatement ps = lopKetNoi.getConnection().prepareStatement("select * from tram where diaChi like '%" + jtfTimKiem.getText() + "%'");
                ResultSet rs = ps.executeQuery();
                while (rs.next()) {
                    tbmBangTram.addRow(new Object[]{rs.getString(1), rs.getString(2)});
                }
            } catch (SQLException ex) {
                Logger.getLogger(JPanelDanhSachTram.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        hangDangChon = -1;
    }//GEN-LAST:event_jtfTimKiemKeyReleased

    private void jtfTimKiemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfTimKiemKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jtfTimKiemKeyPressed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        //        if (hangDangChon == -1) {
        //            JOptionPane.showMessageDialog(this, "Bạn chưa chọn đối tượng trong bảng để xóa!");
        //            return;
        //        }
        //        //kiem tra ma dang chon co nam trong bang khoang cach khong
        //
        //        try {
        //            PreparedStatement ps = lopKetNoi.getConnection().prepareStatement("select * from tram, khoangCachTram where tenTram = ? "
        //                    + "and (tenTram = tenTramBD or tenTram = tenTramKT)");
        //            ps.setString(1, jtbDanhSachTram.getValueAt(hangDangChon, 0).toString());
        //            ResultSet rs = ps.executeQuery();
        //            if (rs.next()) {
        //                if (!rs.getString(1).equals("")) {
        //                    JOptionPane.showMessageDialog(this, "Không thể xóa vì trạm này còn ở bảng khoảng cách");
        //                    return;
        //                }
        //            }
        //        } catch (Exception e) {
        //            e.printStackTrace();
        //        }
        //        int cauTraLoi = JOptionPane.showConfirmDialog(this, "Bạn chắc muốn xóa chứ?", "Thông báo", JOptionPane.YES_NO_OPTION);
        //        if (cauTraLoi == JOptionPane.YES_OPTION) {
        //            String sql = "delete tram where tenTram=?";
        //            try {
        //                PreparedStatement ps = lopKetNoi.getConnection().prepareStatement(sql);
        //                ps.setString(1, jtbDanhSachTram.getValueAt(hangDangChon, 0).toString());
        //                ps.executeUpdate();
        //                JOptionPane.showMessageDialog(this, "Xóa thành công!");
        //                tbmBangTram.removeRow(hangDangChon);
        //                jtfDiaChi.setText("");
        //                jtfTenTram.setText("");
        //                jtbDanhSachTram.clearSelection();
        //                // cap nhat lai cbb khi xoa thanh cong
        //                cbbTramBatDau.removeAllItems();
        //                cbbTramKetThuc.removeAllItems();
        //                ResultSet rs = lopKetNoi.selectQuery("select tenTram from Tram");
        //                while (rs.next()) {
        //                    String tenTram = rs.getString(1);
        //                    cbbTramBatDau.addItem(tenTram);
        //                    cbbTramKetThuc.addItem(tenTram);
        //                }
        //            } catch (HeadlessException | SQLException e) {
        //                e.printStackTrace();
        //            }
        //        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // kiem tra cac rang buoc

        if (!jlbTenTram.getText().equals("")) {

        }
        //        if (jtfTenTram.equals("")) {
        //            JOptionPane.showMessageDialog(this, " Tên trạm không được trống!");
        //            jtfTenTram.requestFocus();
        //            return;
        //        }
        //        if (jtfDiaChi.equals("")) {
        //            JOptionPane.showMessageDialog(this, "Địa chỉ không được trống!");
        //            jtfDiaChi.requestFocus();
        //            return;
        //        }
        //        // sau khi on thoa het thi them vao table va csdl
        //        String sql = "insert into tram values(?,?)";
        //        String tenTram = jtfTenTram.getText().toString().trim().toUpperCase();
        //        String diaChi = jtfDiaChi.getText().toString().trim();
        //        try {
        //            PreparedStatement ps = lopKetNoi.getConnection().prepareStatement(sql);
        //            ps.setString(1, tenTram);
        //            ps.setString(2, diaChi);
        //            ps.executeUpdate();
        //
        //        } catch (Exception e) {
        //            JOptionPane.showMessageDialog(this, "Tên trạm bị trùng");
        //        }
        //        tbmBangTram.addRow(new Object[]{tenTram, diaChi});
        //        JOptionPane.showMessageDialog(this, "Thêm thành công!");
        //
        //        //highlight thằng vừa vào
        //        int tongSoHang = jtbDanhSachTram.getRowCount();
        //        jtbDanhSachTram.scrollRectToVisible(jtbDanhSachTram.getCellRect(tongSoHang - 1, 0, true));
        //        jtbDanhSachTram.clearSelection();
        //        jtbDanhSachTram.addRowSelectionInterval(tongSoHang - 1, tongSoHang - 1); // selection tu hang nao den hang nao
        //        hangDangChon = tongSoHang - 1;
        //        // set rỗng các texxt field
        //        jtfTenTram.setText("");
        //        jtfDiaChi.setText("");
        //        // cap nhat lai cbb
        //        cbbTramBatDau.removeAllItems();
        //        cbbTramKetThuc.removeAllItems();
        //        ResultSet rs = lopKetNoi.selectQuery("select tenTram from Tram");
        //        try {
        //            while (rs.next()) {
        //                tenTram = rs.getString(1);
        //                cbbTramBatDau.addItem(tenTram);
        //                cbbTramKetThuc.addItem(tenTram);
        //            }
        //        } catch (SQLException ex) {
        //            Logger.getLogger(JPanelDanhSachTram.class.getName()).log(Level.SEVERE, null, ex);
        //        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        // kiem tra rang buoc

        if (hangDangChon == -1) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn đối tượng! Vui lòng chọn 1 dòng");
            return;
        }
        String tenTram = jtbDanhSachTram.getValueAt(hangDangChon, 0).toString();
        if (jtfDiaChi.equals("")) {
            JOptionPane.showMessageDialog(this, "Địa chỉ không được trống");
            jtfDiaChi.requestFocus();
            return;

        }
        String sql = "update tram set  diaChi=? where tenTram = ?;";
        String diaChi = jtfDiaChi.getText().trim();
        try {
            PreparedStatement ps = lopKetNoi.getConnection().prepareStatement(sql);
            ps.setString(1, diaChi);
            ps.setString(2, tenTram);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Sửa thành công!");
            jtbDanhSachTram.setValueAt(diaChi, hangDangChon, 1);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void jtfTenTramKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfTenTramKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtfDiaChi.requestFocus();
        }
    }//GEN-LAST:event_jtfTenTramKeyPressed

    private void jtbDanhSachTramMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbDanhSachTramMousePressed
        // TODO add your handling code here:
        hangDangChon = jtbDanhSachTram.getSelectedRow();
        jtfTenTram.setText(jtbDanhSachTram.getValueAt(hangDangChon, 0) + "");
        jtfDiaChi.setText(jtbDanhSachTram.getValueAt(hangDangChon, 1) + "");
    }//GEN-LAST:event_jtbDanhSachTramMousePressed

    private void jtfTenTramKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfTenTramKeyReleased
        // TODO add your handling code here:
        String tenTram = jtfTenTram.getText().toUpperCase();
        if (!tenTram.equals("")) {
            jlbTenTram.setText("");
            try {
                    ResultSet rs = LopKetNoi.select("select * from Tram where tenTram = ?", tenTram );
                    if(rs.next()){
                        jlbTenTram.setText("Tên trạm bị trùng");
                    }
                    else{
                        jlbTenTram.setText("");
                    }
            } catch (Exception e) {
            }
        } else {
            jlbTenTram.setText("Tên trạm không được rỗng");
        }

    }//GEN-LAST:event_jtfTenTramKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbbSapXep;
    private javax.swing.JComboBox<String> cbbTimKiem;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jlbTenTram;
    private javax.swing.JTable jtbDanhSachTram;
    private javax.swing.JTextField jtfDiaChi;
    private javax.swing.JTextField jtfTenTram;
    private javax.swing.JTextField jtfTimKiem;
    // End of variables declaration//GEN-END:variables
}
